### PR TITLE
Implement search neigtborhood on react frontend

### PR DESCRIPTION
**Pull request by couds**
This PR does

- Create 2 new endpints to search neigtborhoods by geo or name
- Implements autocomplete for text search
- Allow the user to select the neighborhood from the map

Note: Also add eslint rules to the backend

### CODE REVIEW

**Comment by cw00dw0rd** [comment]
@couds Thanks for the updates, getting results via neighborhoods is definitely something we wanted to do. 
I have two notes though:
* I had to change the `config/index.js` to get to the `npm` backend server, if not using `docker-compose`. What do you think of using `.env` for this? If leaving it as is seems the best way to handle that is fine, just curious.
* The map doesn't display anything when viewing. Should the `No neighborhood found` update when dragging/clicking? I Will not have time to dig into it until later but perhaps it is an issue due to starting with `npm` vs `docker-compose`?
image

**Comment by couds** [comment]
I forgot to add that the view need to be updated like this

```json
{
  "writebufferIdle": 64,
  "type": "arangosearch",
  "writebufferSizeMax": 33554432,
  "consolidationPolicy": {
    "type": "tier",
    "segmentsBytesFloor": 2097152,
    "segmentsBytesMax": 5368709120,
    "segmentsMax": 10,
    "segmentsMin": 1,
    "minScore": 0
  },
  "primarySort": [],
  "globallyUniqueId": "hBBD5E7538BF1/7888121",
  "id": "7888121",
  "storedValues": [],
  "writebufferActive": 0,
  "consolidationIntervalMsec": 1000,
  "cleanupIntervalStep": 2,
  "commitIntervalMsec": 1000,
  "links": {
    "listings": {
      "analyzers": [
        "identity"
      ],
      "fields": {
        "room_type": {},
        "description": {
          "analyzers": [
            "text_en"
          ]
        },
        "price": {},
        "amenities": {
          "analyzers": [
            "text_en",
            "identity"
          ]
        },
        "host_id": {},
        "location": {
          "analyzers": [
            "geo"
          ]
        }
      },
      "includeAllFields": false,
      "storeValues": "none",
      "trackListPositions": false
    },
    "neighborhoods": {
      "analyzers": [
        "identity"
      ],
      "fields": {
        "properties": {
          "fields": {
            "neighborhood": {
              "analyzers": [
                "text_en"
              ]
            }
          }
        },
        "geometry": {
          "analyzers": [
            "geo"
          ]
        }
      },
      "includeAllFields": false,
      "storeValues": "none",
      "trackListPositions": false
    }
  },
  "primarySortCompression": "lz4"
}
```

**Comment by cw00dw0rd** [comment]
This is very cool! Now I want to add it to the Vue map ;-D

Uploaded new dump that includes the updated view here: [https://drive.google.com/drive/folders/1KF4tkD1pnejx3kroQFMzsedT_bGajww3?usp=sharing](https://drive.google.com/drive/folders/1KF4tkD1pnejx3kroQFMzsedT_bGajww3?usp=sharing)

**Review by cw00dw0rd — APPROVED** [review]
LGTM!

**Pull request merged**
