### PR TITLE
Structured the project with NPM workspaces

### PR DESCRIPTION
**Pull request by lostpebble**
As per https://github.com/cw00dw0rd/ArangoBnB/issues/19, used NPM workspaces to make development more modular.

Moved all the Vue root files into the folder `/workspaces/frontend-vue` and created a new root `package.json` which defines the workspaces.

### CODE REVIEW

**Comment by lostpebble** [comment]
Just an extra note:

* Make sure your NPM version is 7+
* Because of some Vue peer dependency clashes- and NPM 7 being stricter about throwing errors for such things- you need to install with `npm install --legacy-peer-deps` - until we manage to resolve those issues

**Comment by cw00dw0rd** [comment]
I don't mind `--legacy-peer-deps` as a temporary solution but the process for getting react to work seems to have an issue.
If I follow the expected steps react will not start:
1. `npm install --legacy-peer-deps`
2. `npm run serve-react`
<details>
  <summary>Output</summary>
  There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to fix locally.

The react-scripts package provided by Create React App requires a dependency:

  "babel-loader": "8.1.0"

Don't try to install it manually: your package manager does it automatically.
However, a different version of babel-loader was detected higher up in the tree:

  C:\Users\cw00d\ArangoDB\DevelopmentProjects\ArangoSearch\geoView\ArangoBnB\node_modules\babel-loader (version: 8.2.2)

Manually installing incompatible versions is known to cause hard-to-debug issues.

If you would prefer to ignore this check, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That will permanently disable this message but you might encounter other issues.

To fix the dependency tree, try following the steps below in the exact order:

  1. Delete package-lock.json (not package.json!) and/or yarn.lock in your project folder.
  2. Delete node_modules in your project folder.
  3. Remove "babel-loader" from dependencies and/or devDependencies in the package.json file in your project folder.
  4. Run npm install or yarn, depending on the package manager you use.

In most cases, this should be enough to fix the problem.
If this has not helped, there are a few other things you can try:

  5. If you used npm, install yarn (http://yarnpkg.com/) and repeat the above steps with it instead.
     This may help because npm has known issues with package hoisting which may get resolved in future versions.

  6. Check if C:\Users\cw00d\ArangoDB\DevelopmentProjects\ArangoSearch\geoView\ArangoBnB\node_modules\babel-loader is outside your project directory.
     For example, you might have accidentally installed something in your home folder.

  7. Try running npm ls babel-loader in your project folder.
     This will tell you which other package (apart from the expected react-scripts) installed babel-loader.

If nothing else helps, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That would permanently disable this preflight check in case you want to proceed anyway.

P.S. We know this message is long but please read the steps above :-) We hope you find them helpful!
</details>

It seems to be a conflict with a module downloaded due to Vue. If I delete the root `node_modules` folder I am able to start the react app.
I suppose this part isn't a big issue for the Vue side of things but dealing with the different modules in this way seems a bit counter to the idea of the workspaces. What do you think?

**Comment by lostpebble** [comment]
Okay, just checked it out. Looks like NPM workspaces doesn't create multiple versions of dependencies, for what is required inside each package... rather strange.

It seems that the version is only a single patch version away, so its not a big deal- I added in an `.env` file which skips that check for now.

Other option is to use `yarn` for the workspaces, which has different behaviour. I use `yarn` in my projects, but noticed NPM now supports workspaces and people were excited about it, so wanted to give it a try.

Think for now it should be fine with NPM though. Will need to investigate why they don't install the different versions in each package's personal `/node_modules` folders when there is a clash.

**Comment by lostpebble** [comment]
Another option is we keep the structure, so each part is still isolated- but we don't make use of the "global" workspaces install procedure.

We can create scripts in the root which can run `npm install` inside each of the workspace folders- and of course keep the current scripts too, such as `npm run serve` and `npm run serve-react`..

Then they'd all have their dependencies kept isolated only in their folders... none of this hoisting stuff.

**Comment by lostpebble** [comment]
@cw00dw0rd , I just tested it out now and it actually works really nicely.

Users can still do `npm install` in the root and it will install all workspace dependencies- only this time, non of that clashing stuff, so can get rid of the dangerous warning override.

**Comment by lostpebble** [comment]
Another bonus is that we don't have to require NPM 7 and vue can be installed without `--legacy-peer-deps` (though the deps should probably still be fixed, because it will still error on NPM 7 with that).

**Comment by cw00dw0rd** [comment]
This is great! Looks good to me!

**Pull request merged**
